import express from 'express';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import crypto from 'crypto';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import { createClient } from '@supabase/supabase-js';

const __filename=fileURLToPath(import.meta.url);
const __dirname=path.dirname(__filename);
const PORT=Number(process.env.PORT||3000);
const JWT_SECRET=process.env.JWT_SECRET||'';
const SUPABASE_URL=process.env.SUPABASE_URL||'';
const SUPABASE_SERVICE_ROLE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||'';
if(!JWT_SECRET) throw new Error('JWT_SECRET is required.');
if(!SUPABASE_URL||!SUPABASE_SERVICE_ROLE_KEY) console.warn('Supabase is not configured yet. Add SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY to .env.');
const supabase=(SUPABASE_URL&&SUPABASE_SERVICE_ROLE_KEY)?createClient(SUPABASE_URL,SUPABASE_SERVICE_ROLE_KEY,{auth:{autoRefreshToken:false,persistSession:false}}):null;
const app=express();
app.set('trust proxy',1);
app.use(helmet({contentSecurityPolicy:false}));
app.use(express.json({limit:'100kb'}));
app.use(cookieParser());
app.use('/api/auth',rateLimit({windowMs:15*60*1000,max:60,standardHeaders:true,legacyHeaders:false}));
app.use('/api/chat',rateLimit({windowMs:60*1000,max:20,standardHeaders:true,legacyHeaders:false}));

const ACTIVITY_REQUIRED=900;
const TOTAL_REQUIRED=1800;
const MAX_GAP=8;
const AWAY_RESET_SECONDS=300;
const ADMIN_PIN=process.env.ADMIN_PIN||'';

const PASSAGES=[
 {id:'psalm1',title:'Blessed Is the Person Who Delights in God',reference:'Psalm 1:1-6',text:'Blessed is the man that walketh not in the counsel of the ungodly, nor standeth in the way of sinners, nor sitteth in the seat of the scornful. But his delight is in the law of the LORD; and in his law doth he meditate day and night. And he shall be like a tree planted by the rivers of water, that bringeth forth his fruit in his season; his leaf also shall not wither; and whatsoever he doeth shall prosper. The ungodly are not so: but are like the chaff which the wind driveth away. Therefore the ungodly shall not stand in the judgment, nor sinners in the congregation of the righteous. For the LORD knoweth the way of the righteous: but the way of the ungodly shall perish.',questions:[['What does the blessed person delight in?',['The law of the LORD','The counsel of the ungodly','The seat of the scornful','Riches'],0],['When does the blessed person meditate on God’s law?',['Only on Sundays','Day and night','Once a month','Only in trouble'],1],['What is the righteous person compared to?',['A mountain','A tree planted by rivers of water','A bird','A lamp'],1],['What happens to the way of the ungodly?',['It is rewarded','It is hidden','It shall perish','It becomes righteous'],2],['Who knows the way of the righteous?',['The crowd','The king','The LORD','The teacher'],2]]},
 {id:'james1',title:'Be Doers of the Word',reference:'James 1:22-25',text:'But be ye doers of the word, and not hearers only, deceiving your own selves. For if any be a hearer of the word, and not a doer, he is like unto a man beholding his natural face in a glass: For he beholdeth himself, and goeth his way, and straightway forgetteth what manner of man he was. But whoso looketh into the perfect law of liberty, and continueth therein, he being not a forgetful hearer, but a doer of the work, this man shall be blessed in his deed.',questions:[['What must believers be?',['Hearers only','Doers of the word','Judges','Teachers only'],1],['A hearer who does not obey is compared to someone looking into what?',['A river','A mirror','The sky','A book'],1],['What happens to the person who immediately forgets?',['He remembers everything','He forgets what kind of person he was','He becomes famous','He becomes wealthy'],1],['The person who continues in the perfect law is called what?',['A forgetful hearer','A doer of the work','A ruler','A stranger'],1],['What is promised to the doer of the work?',['Blessing in his deed','A crown immediately','No problems','More possessions'],0]]},
 {id:'phil4',title:'Peace Instead of Anxiety',reference:'Philippians 4:6-7',text:'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.',questions:[['What should replace anxious worry?',['Silence','Prayer and supplication with thanksgiving','Anger','Isolation'],1],['To whom should requests be made known?',['Friends only','God','Teachers','Everyone online'],1],['What kind of peace is promised?',['Temporary peace','The peace of God','Political peace','Financial peace'],1],['What will God’s peace keep?',['Only your body','Your house','Your hearts and minds','Your possessions'],2],['Through whom is this peace given?',['Moses','David','Christ Jesus','Paul'],2]]},
 {id:'eph2',title:'Created for Good Works',reference:'Ephesians 2:8-10',text:'For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: Not of works, lest any man should boast. For we are his workmanship, created in Christ Jesus unto good works, which God hath before ordained that we should walk in them.',questions:[['How are we saved?',['By our works alone','By grace through faith','By popularity','By knowledge'],1],['Salvation is described as what?',['A gift of God','A human achievement','A reward for fame','A secret'],0],['What are believers called?',['His workmanship','His competitors','His servants only','His judges'],0],['In whom are believers created for good works?',['Abraham','Moses','Christ Jesus','Solomon'],2],['What should believers walk in?',['Fear','Good works','Pride','Confusion'],1]]},
 {id:'hebrews138',title:'Jesus Never Changes',reference:'Hebrews 13:8',text:'Jesus Christ the same yesterday, and to day, and for ever.',questions:[['Who is the subject of Hebrews 13:8?',['Peter','Jesus Christ','Paul','David'],1],['How is Jesus described?',['Changing every day','The same yesterday, today and forever','Only the same yesterday','Only the same today'],1],['Which time period is included?',['Yesterday only','Today only','Forever only','Yesterday, today and forever'],3],['What does the verse emphasize about Jesus?',['His unchanging nature','His wealth','His age','His location'],0],['Which word completes the statement?',['sometimes','forever','rarely','yesterday only'],1]]}
];

function localDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Lagos',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
function addDays(ds,n){const d=new Date(`${ds}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);}
function todayPassage(){const base=new Date('2026-01-01T00:00:00Z');const today=new Date(`${localDate()}T00:00:00Z`);const n=Math.floor((today-base)/86400000);return PASSAGES[((n%PASSAGES.length)+PASSAGES.length)%PASSAGES.length];}
function publicPassage(p){return {id:p.id,title:p.title,reference:p.reference,text:p.text};}
function tokenFor(user,loginAt){return jwt.sign({sub:user.id,publicId:user.public_id,loginAt},JWT_SECRET,{expiresIn:'7d'});}
function setCookie(res,token){res.cookie('cop_session',token,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:7*24*3600*1000,path:'/'});}
async function currentUser(req){const token=req.cookies?.cop_session;if(!token||!supabase)return null;try{const p=jwt.verify(token,JWT_SECRET);const {data,error}=await supabase.from('users').select('*').eq('id',p.sub).maybeSingle();if(error||!data)return null;return {...data,loginAt:p.loginAt};}catch{return null;}}
async function auth(req,res,next){if(!supabase)return res.status(503).json({error:'Supabase is not configured yet.'});const u=await currentUser(req);if(!u)return res.status(401).json({error:'Please log in first.'});req.user=u;next();}
async function q(table,query){if(!supabase)throw new Error('Supabase is not configured.');const r=await query;if(r.error)throw r.error;return r.data;}
async function getSession(id){const {data,error}=await supabase.from('activity_sessions').select('*').eq('id',id).maybeSingle();if(error)throw error;return data;}
function sessionOut(s){return s&&{id:s.id,kind:s.kind,date:s.date,passageId:s.passage_id,activeSeconds:s.active_seconds,status:s.status,quizScore:s.quiz_score,stoppedAt:s.stopped_at||null};}
async function ensureSession(userId,kind,date,passageId){let {data,error}=await supabase.from('activity_sessions').select('*').eq('user_id',userId).eq('kind',kind).eq('date',date).in('status',['active','quiz','done','stopped']).order('started_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;if(data){if(data.status==='stopped'){const up=await supabase.from('activity_sessions').update({status:'active',stopped_at:null,stop_reason:null,last_heartbeat_at:new Date().toISOString()}).eq('id',data.id).select().single();if(up.error)throw up.error;return up.data;}return data;}const id=crypto.randomUUID();const now=new Date().toISOString();const row={id,user_id:userId,kind,date,passage_id:passageId||null,started_at:now,last_heartbeat_at:now,active_seconds:0,status:'active'};const ins=await supabase.from('activity_sessions').insert(row).select().single();if(ins.error)throw ins.error;return ins.data;}
async function updateHeartbeat(s,active){if(s.status!=='active')return s;const now=new Date();const last=new Date(s.last_heartbeat_at);const gap=(now-last)/1000;let add=0;if(active&&gap>=0&&gap<=MAX_GAP)add=Math.min(MAX_GAP,Math.floor(gap));const activeSeconds=Math.min(ACTIVITY_REQUIRED,(s.active_seconds||0)+add);const upd=await supabase.from('activity_sessions').update({active_seconds:activeSeconds,last_heartbeat_at:now.toISOString()}).eq('id',s.id).select().single();if(upd.error)throw upd.error;return upd.data;}
async function latestRecord(userId,date){const {data,error}=await supabase.from('daily_records').select('*').eq('user_id',userId).eq('date',date).eq('state','active').order('id',{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data;}
async function dailyTotals(userId,date){const {data,error}=await supabase.from('activity_sessions').select('kind,active_seconds').eq('user_id',userId).eq('date',date);if(error)throw error;let readingSeconds=0,prayerSeconds=0;for(const x of data||[]){if(x.kind==='reading')readingSeconds+=Number(x.active_seconds||0);if(x.kind==='prayer')prayerSeconds+=Number(x.active_seconds||0);}return {readingSeconds,prayerSeconds,totalSeconds:Math.min(TOTAL_REQUIRED,readingSeconds+prayerSeconds)};}
async function streak(userId,date){const {data,error}=await supabase.from('daily_records').select('streak,date').eq('user_id',userId).eq('state','active').eq('date',addDays(date,-1)).order('id',{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data?.streak||0;}
async function savePartial(user,reading,prayer){const date=localDate();const totals=await dailyTotals(user.id,date);const existing=await latestRecord(user.id,date);const payload={user_id:user.id,public_id:user.public_id,name:user.name,date,passage_id:reading?.passage_id||prayer?.passage_id||null,passage_reference:reading?todayPassage().reference:(existing?.passage_reference||null),active_reading_seconds:totals.readingSeconds,quiz_score:reading?.quiz_score??existing?.quiz_score??null,active_prayer_seconds:totals.prayerSeconds,reflection:existing?.reflection||null,login_at:user.loginAt,completed_at:new Date().toISOString(),streak:existing?.streak||0,completion_type:'partial',state:'active',cleared_at:null};if(existing){const upd=await supabase.from('daily_records').update(payload).eq('id',existing.id).select().single();if(upd.error)throw upd.error;return upd.data;}const ins=await supabase.from('daily_records').insert(payload).select().single();if(ins.error)throw ins.error;return ins.data;}
async function fullRecord(user,reading,prayer,reflection){const date=localDate();const existing=await latestRecord(user.id,date);const totals=await dailyTotals(user.id,date);const prev=await streak(user.id,date);const st=(existing?.streak||prev)+(!existing?.streak?1:0);const row={user_id:user.id,public_id:user.public_id,name:user.name,date,passage_id:reading.passage_id,passage_reference:todayPassage().reference,active_reading_seconds:totals.readingSeconds,quiz_score:reading.quiz_score,active_prayer_seconds:totals.prayerSeconds,reflection,login_at:user.loginAt,completed_at:new Date().toISOString(),streak:st,completion_type:'full',state:'active',cleared_at:null};if(existing){const upd=await supabase.from('daily_records').update(row).eq('id',existing.id).select().single();if(upd.error)throw upd.error;await supabase.from('users').update({streak:st,last_checkin_date:date}).eq('id',user.id);return upd.data;}const ins=await supabase.from('daily_records').insert(row).select().single();if(ins.error)throw ins.error;await supabase.from('users').update({streak:st,last_checkin_date:date}).eq('id',user.id);return ins.data;}
function recordOut(r){return r&&{id:r.id,name:r.name,publicId:r.public_id,date:r.date,passageReference:r.passage_reference,readingSeconds:r.active_reading_seconds,quizScore:r.quiz_score,prayerSeconds:r.active_prayer_seconds,reflection:r.reflection,loginAt:r.login_at,completedAt:r.completed_at,streak:r.streak,completionType:r.completion_type};}

app.post('/api/auth/register',async(req,res)=>{
  try{
    if(!supabase)return res.status(503).json({error:'Configure Supabase first.'});
    const name=String(req.body?.name||'').trim();
    const password=String(req.body?.password||'');
    if(name.length<2)return res.status(400).json({error:'Name is required.'});
    if(password.length<8)return res.status(400).json({error:'Password must be at least 8 characters.'});

    const wantsAdmin=String(req.body?.adminPin||'').trim();

    if(wantsAdmin&&(!ADMIN_PIN||wantsAdmin!==ADMIN_PIN)){
      return res.status(403).json({
        error:'Incorrect Admin PIN. Leave the Admin PIN blank to register as a normal teen.'
      });
    }

    const isAdmin=Boolean(ADMIN_PIN&&wantsAdmin===ADMIN_PIN);

    const hash=await bcrypt.hash(password,12);

    const {data:ins,error}=await supabase.from('users').insert({name,password_hash:hash,is_admin:isAdmin}).select('id,name,password_hash,streak,created_at,is_admin').single();
    if(error)return res.status(400).json({error:error.message});
    const year=new Intl.DateTimeFormat('en',{timeZone:'Africa/Lagos',year:'numeric'}).format(new Date());
    const publicId=`COP-${year}-${String(ins.id).padStart(6,'0')}`;
    const upd=await supabase.from('users').update({public_id:publicId}).eq('id',ins.id).select().single();
    if(upd.error)throw upd.error;
    const loginAt=new Date().toISOString();
    setCookie(res,tokenFor(upd.data,loginAt));
    res.json({user:{id:publicId,name:upd.data.name,streak:upd.data.streak||0,loginAt,isAdmin:Boolean(upd.data.is_admin)}});
  }catch(e){
    res.status(500).json({error:'Registration failed: '+e.message});
  }
});

app.post('/api/auth/login',async(req,res)=>{try{if(!supabase)return res.status(503).json({error:'Configure Supabase first.'});const id=String(req.body?.id||'').trim().toUpperCase();const password=String(req.body?.password||'');const {data,error}=await supabase.from('users').select('*').eq('public_id',id).maybeSingle();if(error)throw error;if(!data||!(await bcrypt.compare(password,data.password_hash)))return res.status(401).json({error:'Invalid Teen ID or password.'});const loginAt=new Date().toISOString();setCookie(res,tokenFor(data,loginAt));res.json({user:{id:data.public_id,name:data.name,streak:data.streak||0,loginAt,isAdmin:Boolean(data.is_admin)}});}catch(e){res.status(500).json({error:'Login failed: '+e.message});}});
app.get('/api/auth/me',async(req,res)=>{const u=await currentUser(req);if(!u)return res.json({authenticated:false});res.json({authenticated:true,user:{id:u.public_id,name:u.name,streak:u.streak||0,loginAt:u.loginAt,isAdmin:Boolean(u.is_admin)}});});
app.post('/api/auth/logout',(req,res)=>{res.clearCookie('cop_session',{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',path:'/'});res.json({ok:true});});
app.get('/logout',(req,res)=>{res.clearCookie('cop_session',{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',path:'/'});res.redirect('/');});

app.get('/api/daily/passage',auth,async(req,res)=>{const p=todayPassage();res.json({passage:{...publicPassage(p),date:localDate()}});});
app.get('/api/progress',auth,async(req,res)=>{try{const date=localDate();const {data:recs,error}=await supabase.from('daily_records').select('*').eq('user_id',req.user.id).eq('date',date).eq('state','active').order('id',{ascending:false}).limit(1);if(error)throw error;if(recs?.[0])return res.json({completed:true,record:recordOut(recs[0])});const {data:sessions,error:se}=await supabase.from('activity_sessions').select('*').eq('user_id',req.user.id).eq('date',date).order('started_at',{ascending:false});if(se)throw se;const reading=sessions?.find(s=>s.kind==='reading');const prayer=sessions?.find(s=>s.kind==='prayer');const reflection=(await supabase.from('reflections').select('*').eq('user_id',req.user.id).eq('date',date).maybeSingle()).data;const totals=await dailyTotals(req.user.id,date);let quiz=null;if(reading?.quiz_ids){quiz={questions:JSON.parse(reading.quiz_ids).map(x=>({id:x.id,question:x.question,options:x.options}))};}res.json({completed:false,reading:sessionOut(reading),prayer:sessionOut(prayer),quiz,reflection,...totals,totalReached:totals.totalSeconds>=TOTAL_REQUIRED});}catch(e){res.status(500).json({error:e.message});}});

app.post('/api/reading/start',auth,async(req,res)=>{try{const date=localDate();if(await latestRecord(req.user.id,date))return res.status(409).json({error:'You have already checked in today. Please come back tomorrow.'});const s=await ensureSession(req.user.id,'reading',date,todayPassage().id);res.json({session:sessionOut(s)});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/reading/heartbeat',auth,async(req,res)=>{try{const s=await getSession(String(req.body?.sessionId||''));if(!s||s.user_id!==req.user.id||s.kind!=='reading')return res.status(404).json({error:'Reading session not found.'});const u=await updateHeartbeat(s,Boolean(req.body?.active));const totals=await dailyTotals(req.user.id,localDate());res.json({session:sessionOut(u),...totals,totalReached:totals.totalSeconds>=TOTAL_REQUIRED});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/reading/stop',auth,async(req,res)=>{try{const s=await getSession(String(req.body?.sessionId||''));if(!s||s.user_id!==req.user.id||s.kind!=='reading')return res.status(404).json({error:'Reading session not found.'});const u=await updateHeartbeat(s,active=false);const x=await supabase.from('activity_sessions').update({status:'stopped',stopped_at:new Date().toISOString(),stop_reason:'user'}).eq('id',s.id).select().single();if(x.error)throw x.error;res.json({session:sessionOut(x.data)});}catch(e){res.status(500).json({error:e.message});}});

app.post('/api/reading/quiz',auth,async(req,res)=>{try{const date=localDate();const session=await getSession(String(req.body?.sessionId||''));if(!session||session.user_id!==req.user.id||session.kind!=='reading')return res.status(404).json({error:'Reading session not found.'});const p=findPassageServer(session.passage_id);const totals=await dailyTotals(req.user.id,date);if(totals.readingSeconds<ACTIVITY_REQUIRED)return res.status(400).json({error:'Complete 15 active minutes of Bible reading first.'});if(!req.body.answers){const qs=[...p.questions].sort(()=>Math.random()-.5).slice(0,4).map((x,i)=>({id:`${p.id}-${crypto.randomUUID()}`,question:x[0],options:x[1],answer:x[2]}));const safe=qs.map(q=>({id:q.id,question:q.question,options:q.options}));await supabase.from('activity_sessions').update({quiz_ids:JSON.stringify(qs)}).eq('id',session.id);return res.json({questions:safe});}const quiz=(session.quiz_ids?JSON.parse(session.quiz_ids):[]);const answers=req.body.answers||{};let score=0;for(const q of quiz)if(Number(answers[q.id])===q.answer)score++;if(score<3)return res.status(400).json({error:`Score ${score}/4. You need at least 3/4. Please review the passage and try again.`});const x=await supabase.from('activity_sessions').update({quiz_score:score,status:'done'}).eq('id',session.id).select().single();if(x.error)throw x.error;res.json({score,total:4});}catch(e){res.status(500).json({error:e.message});}});
function findPassageServer(id){return PASSAGES.find(p=>p.id===id)||todayPassage();}

app.post('/api/prayer/start',auth,async(req,res)=>{try{const date=localDate();if(await latestRecord(req.user.id,date))return res.status(409).json({error:'You have already checked in today. Please come back tomorrow.'});const s=await ensureSession(req.user.id,'prayer',date,null);const x=await supabase.from('activity_sessions').update({status:'active'}).eq('id',s.id).select().single();if(x.error)throw x.error;res.json({session:sessionOut(x.data)});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/prayer/heartbeat',auth,async(req,res)=>{try{const s=await getSession(String(req.body?.sessionId||''));if(!s||s.user_id!==req.user.id||s.kind!=='prayer')return res.status(404).json({error:'Prayer session not found.'});const u=await updateHeartbeat(s,Boolean(req.body?.active));const totals=await dailyTotals(req.user.id,localDate());res.json({session:sessionOut(u),...totals,totalReached:totals.totalSeconds>=TOTAL_REQUIRED});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/prayer/stop',auth,async(req,res)=>{try{const s=await getSession(String(req.body?.sessionId||''));if(!s||s.user_id!==req.user.id||s.kind!=='prayer')return res.status(404).json({error:'Prayer session not found.'});await updateHeartbeat(s,false);const x=await supabase.from('activity_sessions').update({status:'stopped',stopped_at:new Date().toISOString(),stop_reason:'user'}).eq('id',s.id).select().single();if(x.error)throw x.error;res.json({session:sessionOut(x.data)});}catch(e){res.status(500).json({error:e.message});}});

app.post('/api/reflection',auth,async(req,res)=>{try{const text=String(req.body?.reflection||'').trim();if(text.length<10||text.length>600)return res.status(400).json({error:'Please provide a short reflection of 10–600 characters.'});const date=localDate();const x=await supabase.from('reflections').upsert({user_id:req.user.id,date,text,created_at:new Date().toISOString()},{onConflict:'user_id,date'}).select().single();if(x.error)throw x.error;res.json({reflection:{text:x.data.text}});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/checkin/partial',auth,async(req,res)=>{try{const date=localDate();const reading=(await supabase.from('activity_sessions').select('*').eq('user_id',req.user.id).eq('date',date).eq('kind','reading').order('started_at',{ascending:false}).limit(1).maybeSingle()).data;const prayer=(await supabase.from('activity_sessions').select('*').eq('user_id',req.user.id).eq('date',date).eq('kind','prayer').order('started_at',{ascending:false}).limit(1).maybeSingle()).data;const r=await savePartial(req.user,reading,prayer);res.json({record:recordOut(r)});}catch(e){res.status(500).json({error:e.message});}});
app.post('/api/checkin/done',auth,async(req,res)=>{try{const date=localDate();const existing=await latestRecord(req.user.id,date);if(existing)return res.status(409).json({error:'You have already checked in today. Please come back tomorrow.'});const ids=[String(req.body?.readingSessionId||''),String(req.body?.prayerSessionId||'')].filter(Boolean);for(const id of ids){const sess=await getSession(id);if(sess&&sess.user_id===req.user.id&&sess.date===date&&['reading','prayer'].includes(sess.kind)&&sess.status==='active')await updateHeartbeat(sess,true);}const now=new Date().toISOString();for(const id of ids){const x=await supabase.from('activity_sessions').update({status:'stopped',stopped_at:now,stop_reason:'done-for-today'}).eq('id',id).eq('user_id',req.user.id);if(x.error)throw x.error;}const reading=(await supabase.from('activity_sessions').select('*').eq('user_id',req.user.id).eq('date',date).eq('kind','reading').order('started_at',{ascending:false}).limit(1).maybeSingle()).data;const prayer=(await supabase.from('activity_sessions').select('*').eq('user_id',req.user.id).eq('date',date).eq('kind','prayer').order('started_at',{ascending:false}).limit(1).maybeSingle()).data;const prev=await streak(req.user.id,date);const r0=await savePartial(req.user,reading,prayer);const nextStreak=(prev||0)+1;const ur=await supabase.from('daily_records').update({streak:nextStreak}).eq('id',r0.id).select().single();if(ur.error)throw ur.error;await supabase.from('users').update({streak:nextStreak,last_checkin_date:date}).eq('id',req.user.id);res.json({record:recordOut(ur.data)});}catch(e){console.error(e);res.status(500).json({error:e.message});}});
app.post('/api/checkin/full',auth,async(req,res)=>{try{const date=localDate();const existing=await latestRecord(req.user.id,date);if(existing)return res.status(409).json({error:'You have already checked in today.'});const reading=(await supabase.from('activity_sessions').select('*').eq('user_id',req.user.id).eq('date',date).eq('kind','reading').order('started_at',{ascending:false}).limit(1).maybeSingle()).data;const prayer=(await supabase.from('activity_sessions').select('*').eq('user_id',req.user.id).eq('date',date).eq('kind','prayer').order('started_at',{ascending:false}).limit(1).maybeSingle()).data;const reflection=(await supabase.from('reflections').select('*').eq('user_id',req.user.id).eq('date',date).maybeSingle()).data;const totals=await dailyTotals(req.user.id,date);if(!reading||!reading.quiz_score||reading.quiz_score<3)return res.status(400).json({error:'Complete Bible verification first.'});if(totals.readingSeconds<ACTIVITY_REQUIRED)return res.status(400).json({error:'Complete 15 active minutes of Bible reading first.'});if(!reflection)return res.status(400).json({error:'Submit your reflection first.'});const r=await fullRecord(req.user,reading,prayer,reflection.text);res.json({record:recordOut(r)});}catch(e){res.status(500).json({error:e.message});}});

app.get('/api/admin/history',auth,async(req,res)=>{try{if(!req.user.is_admin)return res.status(403).json({error:'Admin access only.'});const r=await supabase.from('daily_records').select('*').order('date',{ascending:false}).order('name',{ascending:true});if(r.error)throw r.error;const grouped={};for(const x of (r.data||[])){if(!grouped[x.date])grouped[x.date]=[];grouped[x.date].push(recordOut(x));}res.json({dates:Object.keys(grouped).sort((a,b)=>b.localeCompare(a)).map(date=>({date,records:grouped[date].sort((a,b)=>a.name.localeCompare(b.name))}))});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/admin/summary',auth,async(req,res)=>{try{if(!req.user.is_admin)return res.status(403).json({error:'Admin access only.'});const today=localDate();const users=await supabase.from('users').select('id,public_id,name,is_admin,created_at').order('name',{ascending:true});if(users.error)throw users.error;const todayRecs=await supabase.from('daily_records').select('user_id,public_id,name,active_reading_seconds,active_prayer_seconds,completion_type,completed_at').eq('date',today).order('name',{ascending:true});if(todayRecs.error)throw todayRecs.error;res.json({today,users:users.data||[],todayRecords:todayRecs.data||[]});}catch(e){res.status(500).json({error:e.message});}});

app.post('/api/activity/reset-after-away',auth,async(req,res)=>{try{const id=String(req.body?.sessionId||'');const s=await getSession(id);if(!s||s.user_id!==req.user.id||!['reading','prayer'].includes(s.kind))return res.status(404).json({error:'Activity session not found.'});const now=new Date().toISOString();const x=await supabase.from('activity_sessions').update({active_seconds:0,last_heartbeat_at:now,stopped_at:null,stop_reason:'reset-after-away',status:'stopped'}).eq('id',id).select().single();if(x.error)throw x.error;res.json({session:sessionOut(x.data),message:'More than 5 minutes away. This timer has restarted from 00:00.'});}catch(e){res.status(500).json({error:e.message});}});

app.post('/api/daily/reset',auth,async(req,res)=>{try{const date=localDate();const active=await latestRecord(req.user.id,date);const reading=(await supabase.from('activity_sessions').select('active_seconds').eq('user_id',req.user.id).eq('date',date).eq('kind','reading').order('started_at',{ascending:false}).limit(1).maybeSingle()).data;const prayer=(await supabase.from('activity_sessions').select('active_seconds').eq('user_id',req.user.id).eq('date',date).eq('kind','prayer').order('started_at',{ascending:false}).limit(1).maybeSingle()).data;if(active){await supabase.from('daily_records').update({state:'cleared',cleared_at:new Date().toISOString()}).eq('id',active.id);}await supabase.from('reset_events').insert({user_id:req.user.id,public_id:req.user.public_id,name:req.user.name,date,cleared_at:new Date().toISOString(),reading_seconds:reading?.active_seconds||0,prayer_seconds:prayer?.active_seconds||0,completion_type:active?.completion_type||'none'});await supabase.from('activity_sessions').delete().eq('user_id',req.user.id).eq('date',date);await supabase.from('reflections').delete().eq('user_id',req.user.id).eq('date',date);res.json({ok:true});}catch(e){res.status(500).json({error:e.message});}});

app.get('/api/checkins',auth,async(req,res)=>{try{const date=localDate();const r=await supabase.from('daily_records').select('*').eq('date',date).eq('state','active').order('completed_at',{ascending:false});if(r.error)throw r.error;res.json({events:(r.data||[]).map(x=>({eventType:'checkin',name:x.name,publicId:x.public_id,completionType:x.completion_type,readingSeconds:x.active_reading_seconds,prayerSeconds:x.active_prayer_seconds,loginAt:x.login_at,timestamp:x.completed_at}))});}catch(e){res.status(500).json({error:e.message});}});
app.get('/api/history',auth,async(req,res)=>{try{const r=await supabase.from('daily_records').select('*').eq('user_id',req.user.id).order('date',{ascending:false}).limit(60);if(r.error)throw r.error;res.json({records:(r.data||[]).map(recordOut)});}catch(e){res.status(500).json({error:e.message});}});

function danielAnswer(question){
  const q=String(question||'').toLowerCase().replace(/[^a-z0-9: ?'-]/g,' ').replace(/\s+/g,' ').trim();
  const hit=(...terms)=>terms.some(t=>q.includes(t));
  const answers=[
    [['hebrews 13:8','heb 13:8'], 'Hebrews 13:8 says Jesus Christ is the same yesterday, today and forever. The key idea is His unchanging character. People and circumstances can change, but Jesus remains faithful. For a teen, that can be a source of confidence when school, friendships or plans feel uncertain.'],
    [['john 3:16','god so loved'], 'John 3:16 is about God’s love, the gift of His Son, faith in Jesus and eternal life. The verse shows that salvation starts with God’s love and grace. A practical question to ask is: How should knowing God loves me change the way I treat Him and other people?'],
    [['psalm 23','psalm 23'], 'Psalm 23 pictures the Lord as a shepherd who guides, feeds and protects His people. It does not promise a life with no trouble; it shows that God is present even in dark valleys. The encouragement is to trust His guidance rather than letting fear make every decision.'],
    [['psalm 1'], 'Psalm 1 contrasts two ways of living: being shaped by ungodly influence or being rooted in God’s Word. The person who delights in God’s instruction is pictured like a healthy tree planted by water. Your influences matter — friends, media and advice can shape your choices.'],
    [['proverbs 3:5','trust in the lord'], 'Proverbs 3:5-6 teaches us to trust the Lord rather than depending only on our own understanding. It does not mean ignoring wisdom; it means putting God first, praying, learning His Word and allowing Him to direct our choices.'],
    [['james 1:5','wisdom'], 'James 1:5 says that anyone who lacks wisdom should ask God, who gives generously. When you are unsure what to do, pray honestly, search Scripture, and seek wise counsel from a trusted Christian adult.'],
    [['james 1:22','doers of the word'], 'James 1:22 teaches that hearing God’s Word should lead to action. Bible knowledge is valuable, but discipleship also means obeying what you learn. Ask: What is one thing I can practise today because of what I read?'],
    [['philippians 4:6','anxiety','worried','worry'], 'Philippians 4:6-7 teaches us to bring worries to God in prayer with thanksgiving. It does not tell you to pretend problems do not exist. It teaches you to bring them honestly to God and trust Him with them.'],
    [['ephesians 2:8','saved by grace'], 'Ephesians 2:8-10 teaches that salvation is by grace through faith — God’s gift. Good works do not buy salvation; they are part of the new life God calls believers to live.'],
    [['romans 12:2','renew your mind','renewed mind'], 'Romans 12:2 speaks about being transformed by the renewing of your mind. For a teenager, that includes paying attention to what shapes your thinking — Scripture, friendships, entertainment and social media — and choosing what helps you think in ways that honour God.'],
    [['1 corinthians 10:13','temptation'], '1 Corinthians 10:13 teaches that temptation is common to people and that God is faithful. It points to a way of escape. When temptation comes, step away from the situation, pray, choose a wise response and involve a trusted adult when you need support.'],
    [['galatians 5','fruit of the spirit','fruit of the spirit'], 'Galatians 5 describes the fruit of the Spirit: love, joy, peace, patience, kindness, goodness, faithfulness, gentleness and self-control. These qualities show what spiritual growth looks like in everyday behaviour, not just in church activities.'],
    [['holy spirit','holy ghost'], 'The Holy Spirit is God’s Spirit who helps believers know, obey and live for Christ. Jesus teaches about the Spirit in John 14-16, and Galatians 5 describes the fruit He produces in a believer’s life.'],
    [['forgive','forgiveness'], 'Biblical forgiveness means releasing personal revenge and choosing not to keep paying someone back for a wrong. Forgiveness does not mean saying harmful behaviour was acceptable or staying in an unsafe situation. For serious harm or abuse, tell a trusted adult and seek appropriate protection.'],
    [['sin'], 'Sin is disobedience to God — thoughts, choices or actions that go against His will. The Christian response is not to hide. We confess, turn back to God, receive His forgiveness and learn to make different choices with His help.'],
    [['faith'], 'Faith is trusting God and relying on Him. Biblical faith is not pretending problems are not real. It means choosing to trust God, believe His promises and obey His Word even when you cannot see the whole picture yet.'],
    [['how do i pray','how to pray','pray','prayer'], 'You can pray simply and honestly. You can thank God, confess sin, ask for help, pray for family and friends, pray for people who need help, and surrender your plans to Him. You do not need complicated words; sincerity matters more than sounding impressive.'],
    [['purpose','my purpose'], 'A good biblical starting point for purpose is to know God, grow in Christlike character, use your gifts to serve others and live faithfully where God has placed you. Purpose usually becomes clearer through prayer, Scripture, service and wise guidance.'],
    [['love','loving others'], 'Jesus teaches His followers to love God and love their neighbours. Christian love is more than a feeling: it can look like honesty, kindness, patience, forgiveness, service and refusing to harm others.'],
    [['friendship','friends','best friend'], 'Good friendships should move you toward what is wise and godly rather than constantly pulling you away from your values. Look for friends who can tell you the truth with kindness, celebrate your growth and respect healthy boundaries.'],
    [['dating','relationship','boyfriend','girlfriend'], 'A healthy Christian relationship should include respect, honesty, wise boundaries, self-control and room for both people to grow in their faith. You do not need to rush a relationship to prove your worth. Talking with a trusted adult can also bring helpful perspective.'],
    [['bible','scripture','word of god'], 'The Bible is a collection of writings that Christians receive as Scripture. A simple way to study it is to read the passage carefully, notice repeated ideas, ask what it teaches about God and people, and then ask how you should respond.'],
    [['gospel','good news'], 'The gospel is the good news about Jesus Christ: His life, death and resurrection, and God’s invitation to turn to Him and trust Him. It is not merely advice for becoming a better person; it is news about what God has done through Christ.'],
    [['salvation','saved'], 'In Christian teaching, salvation is God rescuing people from sin and bringing them into a restored relationship with Him through Jesus Christ. Scripture emphasizes God’s grace and calls people to respond with faith and repentance.'],
    [['discipline','discipleship'], 'Christian discipline means training your life toward faithfulness. Small habits matter: regular Bible reading, prayer, truthful speech, serving others, managing your time wisely and returning to God when you fail.'],
    [['fear','afraid'], 'Fear can be real without becoming your master. Scripture repeatedly points people toward trusting God, praying, remembering His character and seeking wise support. Courage is not always the absence of fear; sometimes it is choosing what is right while you are still afraid.'],
    [['anger'], 'Anger is a real emotion, but Scripture calls believers to control how they respond to it. Pause, breathe, pray, avoid harmful words or actions, and talk about the situation when you are calm.'],
    [['lonely','loneliness'], 'Feeling lonely does not mean you are forgotten by God or that you must handle everything alone. Reach out to a trusted person, stay connected to healthy community, pray honestly and take one small step toward meaningful connection.']
  ];

  for(const [terms,answer] of answers) if(hit(...terms)) return answer;

  const ref=PASSAGES.find(p=>q.includes(p.reference.toLowerCase())||q.includes(p.id));

  if(ref) return `${ref.title} (${ref.reference})

${ref.text}

Try these questions: What does this passage show about God? What should it change in your choices? What is one action you can take today?`;

  const starters=[
    'That is a thoughtful question. A helpful biblical way to look at it is to start with God’s character, then ask what Scripture teaches about the situation and what a wise next step would be.',
    'Good question. The Bible often gives us a principle rather than a one-line answer. Look for what Scripture says about love, truth, wisdom, self-control and how we treat other people.',
    'Let’s work through it together. First ask: What does the Bible clearly say? Then ask: What part is interpretation or personal application? Finally, what action would honour Christ?',
    'That question can be explored from several Bible passages. A useful study habit is to compare a few passages, check their context, and then pray about how the teaching applies to your situation.'
  ];

  let idx=0;
  for(const ch of q) idx=(idx+ch.charCodeAt(0))%starters.length;

  return `${starters[idx]}

You can also give me a Bible verse, chapter or specific topic, and I’ll help you study it. For example: “Explain Romans 12:2” or “How can I deal with fear?”`;
}

app.post('/api/chat',auth,async(req,res)=>{try{const question=String(req.body?.question||'').trim();if(!question)return res.status(400).json({error:'Question required.'});res.json({answer:danielAnswer(question)});}catch(e){console.error(e);res.status(500).json({error:'Daniel GPT is temporarily unavailable.'});}});

app.use(express.static(path.join(__dirname,'public')));
app.use((req,res,next)=>{ if(req.method==='GET' && !req.path.startsWith('/api/')) return res.sendFile(path.join(__dirname,'public','index.html')); next(); });

app.listen(PORT,()=>console.log(`City of Praise Teens server running on port ${PORT}`));
