-- CITY OF PRAISE TEENS - SUPABASE DATABASE
-- Run this entire file in Supabase > SQL Editor.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  public_id text unique,
  name text not null,
  password_hash text not null,
  created_at timestamptz not null default now(),
  last_login_at timestamptz,
  streak integer not null default 0,
  last_checkin_date date
);

alter table public.users enable row level security;

create table if not exists public.activity_sessions (
  id uuid primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  kind text not null check (kind in ('reading','prayer')),
  date date not null,
  passage_id text,
  started_at timestamptz not null default now(),
  last_heartbeat_at timestamptz not null default now(),
  active_seconds integer not null default 0,
  status text not null default 'active',
  quiz_ids jsonb,
  quiz_score integer,
  completed_at timestamptz,
  stopped_at timestamptz,
  stop_reason text
);

alter table public.activity_sessions enable row level security;

create table if not exists public.reflections (
  user_id bigint not null references public.users(id) on delete cascade,
  date date not null,
  text text not null,
  created_at timestamptz not null default now(),
  primary key (user_id,date)
);

alter table public.reflections enable row level security;

create table if not exists public.daily_records (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  public_id text not null,
  name text not null,
  date date not null,
  passage_id text,
  passage_reference text,
  active_reading_seconds integer not null default 0,
  quiz_score integer,
  active_prayer_seconds integer not null default 0,
  reflection text,
  login_at timestamptz not null,
  completed_at timestamptz not null default now(),
  streak integer not null default 0,
  completion_type text not null,
  state text not null default 'active',
  cleared_at timestamptz
);

alter table public.daily_records enable row level security;

create table if not exists public.reset_events (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  public_id text not null,
  name text not null,
  date date not null,
  cleared_at timestamptz not null default now(),
  reading_seconds integer not null default 0,
  prayer_seconds integer not null default 0,
  completion_type text not null
);

alter table public.reset_events enable row level security;

create index if not exists idx_sessions_user_date on public.activity_sessions(user_id,date);
create index if not exists idx_records_date on public.daily_records(date,state);
create index if not exists idx_resets_date on public.reset_events(date);

-- The browser never talks directly to these tables. The Node server uses the Supabase service-role key.
-- Therefore no public/anon table policies are needed for this architecture.
